name: Docker Build

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'model.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build -t model:latest -f Dockerfile .
      
      - name: Test the Docker image
        run: docker run model:latest
