name: Evaluate Model

on:
  push:
    branches: [main]
    paths:
      - 'model.py'
      - 'metrics.py'

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Evaluate model
        run: python metrics.py

      - name: Check metrics threshold
        run: |
          ACCURACY=$(python -c "import json; data=json.load(open('metrics.json')); print(data['accuracy'])")
          echo "Model accuracy: $ACCURACY"
          if (( $(echo "$ACCURACY < 0.9" | bc -l) )); then
            echo "❌ Model accuracy below threshold (0.9)"
            exit 1
          else
            echo "✅ Model accuracy above threshold (0.9)"
          fi
          
      - name: Upload metrics
        uses: actions/upload-artifact@v4

        with:
          name: model-metrics
          path: metrics.json
